version: "3.4"

services:
  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: springboot-samples/data-jpa
    ports:
      - 8080:8080
    environment:
      - DB_JDBC_URL=${DB_JDBC_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - APPLICATIONINSIGHTS_CONNECTION_STRING=${APPLICATIONINSIGHTS_CONNECTION_STRING}
